#!/usr/bin/env -S deno run --allow-read --allow-write
/**
 * Writes `create/generated_files.ts`, the file map `deno create` scaffolds
 * from.
 *
 * Sources are `examples/starter/` (the app) and `create/overlay/` (agent
 * instruction files, which cannot sit inside the starter because nested
 * `AGENTS.md`, `CLAUDE.md`, `.cursor/rules` and `.claude/rules` would apply to
 * this checkout). Binary files are listed by path and fetched from
 * https://dashi.run at create time, so the starter's copies must also be
 * deployed there. `$DASHI_APP_NAME` and `$DASHI_VERSION` stay as placeholders
 * for `create/mod.ts`.
 *
 *   deno task create:gen
 *   deno task create:gen:check
 */

import rootConfig from "../deno.json" with { type: "json" };
import starterConfig from "../examples/starter/deno.json" with {
  type: "json",
};

const ROOT = new URL("../", import.meta.url);
const STARTER = new URL("examples/starter/", ROOT);
const OVERLAY = new URL("create/overlay/", ROOT);
const OUT = new URL("create/generated_files.ts", ROOT);

const SKIP = new Set(["node_modules", "generated", ".deno", "deno.lock"]);

const utf8 = new TextDecoder("utf-8", { fatal: true });

async function walk(dir: URL, rel: string, files: string[]): Promise<void> {
  for await (const entry of Deno.readDir(dir)) {
    if (SKIP.has(entry.name)) {
      continue;
    }
    const childRel = rel === "" ? entry.name : `${rel}/${entry.name}`;
    if (entry.isDirectory) {
      await walk(new URL(`${entry.name}/`, dir), childRel, files);
    } else if (entry.isFile) {
      files.push(childRel);
    }
  }
}

function consumerDenoJson(): string {
  const imports: Record<string, string> = {
    dashi: `jsr:${rootConfig.name}@^$DASHI_VERSION`,
  };
  for (const [key, value] of Object.entries(starterConfig.imports)) {
    if (key !== "dashi" && !key.startsWith("dashi/")) {
      imports[key] = value;
    }
  }
  const { compilerOptions, ...rest } = starterConfig;
  // `unstable` and `nodeModulesDir` are root-only fields in a workspace, so
  // the starter member cannot carry them. Tailwind resolves
  // `@import "tailwindcss"` through node_modules, hence "auto".
  const config = {
    compilerOptions,
    unstable: rootConfig.unstable,
    nodeModulesDir: "auto",
    ...rest,
    imports,
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

async function readOverlay(name: string): Promise<string> {
  return await Deno.readTextFile(new URL(name, OVERLAY));
}

async function generate(): Promise<string> {
  const textFiles = new Map<string, string>();
  const remoteFiles: string[] = [];

  const paths: string[] = [];
  await walk(STARTER, "", paths);
  for (const rel of paths) {
    if (rel === "deno.json") {
      textFiles.set(rel, consumerDenoJson());
      continue;
    }
    const bytes = await Deno.readFile(new URL(rel, STARTER));
    try {
      textFiles.set(rel, utf8.decode(bytes));
    } catch {
      remoteFiles.push(rel);
    }
  }

  textFiles.set("AGENTS.md", await readOverlay("AGENTS.md"));
  textFiles.set("CLAUDE.md", "@AGENTS.md\n");
  const ruleBody = await readOverlay("app-layout.md");
  textFiles.set(
    ".cursor/rules/app-layout.mdc",
    `---\ndescription: Dashi app layout and conventions\nalwaysApply: true\n---\n\n${ruleBody}`,
  );
  textFiles.set(
    ".claude/rules/app-layout.md",
    `---\nalwaysApply: true\n---\n\n${ruleBody}`,
  );

  const textEntries = [...textFiles.keys()].sort().map((key) =>
    `  ${JSON.stringify(key)}: ${JSON.stringify(textFiles.get(key))},\n`
  ).join("");
  const remoteEntries = remoteFiles.sort().map((path) =>
    `  ${JSON.stringify(path)},\n`
  ).join("");

  return `// Generated by scripts/gen_create_template.ts from examples/starter and
// create/overlay. Do not edit; run \`deno task create:gen\`.

/**
 * Text files of a new app, keyed by path. \`$DASHI_APP_NAME\` and
 * \`$DASHI_VERSION\` are substituted at create time.
 */
export const textFiles: Record<string, string> = {
${textEntries}};

/** Binary files of a new app, fetched from https://dashi.run/<path>. */
export const remoteFiles: string[] = [
${remoteEntries}];
`;
}

if (import.meta.main) {
  const output = await generate();
  if (Deno.args.includes("--check")) {
    let current = "";
    try {
      current = await Deno.readTextFile(OUT);
    } catch (error) {
      if (!(error instanceof Deno.errors.NotFound)) {
        throw error;
      }
    }
    if (current !== output) {
      console.error(
        "create/generated_files.ts is out of date. Run `deno task create:gen`.",
      );
      Deno.exit(1);
    }
  } else {
    await Deno.writeTextFile(OUT, output);
  }
}
